import type { Metadata } from 'next';
// import Head from 'next/head';
import { Geist, Geist_Mono } from 'next/font/google';
import { GlobalStyles } from '@/app/styles/Global-Styles';
import StyledComponentsRegistry from '@/lib/styled-components-registry';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <GlobalStyles />
        <body>{children}</body>
      </StyledComponentsRegistry>
    </html>
  );
}
