// 'use client'

import type { Metadata } from 'next';
// import Head from 'next/head';
import { ThemeProvider } from 'styled-components';
import { GlobalStyles } from '@/app/styles/Global-Styles';
import StyledComponentsRegistry from '@/lib/styled-components-registry';
import { theme } from '@/app/styles/theme';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <ThemeProvider theme={theme}>
            <GlobalStyles />
            {children}
          </ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
